# 项目配置
project:
  name: "CatDog_Classification"
  author: "Xu Guangyuan"
  date: "2025/8/9"

# 数据配置
data:
  train_zip_path: "data/raw/train.zip"
  test_zip_path: "data/raw/test.zip"
  extract_dir: "data/raw/temp_extract"
  raw_cats_dir: "data/raw/cats"
  raw_dogs_dir: "data/raw/dogs"
  train_dir: "data/processed/cats_vs_dogs/train"
  val_dir: "data/processed/cats_vs_dogs/val"
  test_dir: "data/processed/cats_vs_dogs/test"
  val_ratio: 0.2
  img_size: 224

# 训练配置
training:
  img_size: 224
  batch_size: 32
  epochs: 100 
  lr: 0.0001
  train_dir: "data/processed/cats_vs_dogs/train"
  val_dir: "data/processed/cats_vs_dogs/val"
  model_save_dir: "models"
  results_dir: "results"

# 测试配置
testing:
  model_load_dir: "models"
  model_name: "best_model.pth"
  img_size: 224
  batch_size: 32
  val_dir: "data/processed/cats_vs_dogs/val"  # 使用验证集作为测试集
  results_dir: "results"

# 预测配置
prediction:
  model_load_dir: "models"
  model_name: "best_model.pth"
  img_size: 224